"""MUSHY-150: can frank RECOVER a structure that is provably there?

frank is the black-box entry, and on real data it fitted train ~3x better than
charlie and still came 6th on test -- it memorised 83 days. That leaves the
frank numbers unreadable, because two opposite stories explain them:

  (a) frank's architecture/optimiser cannot find structure at all, in which
      case every frank number in the bake-off is an optimiser artifact, or
  (b) frank is fine and the CORPUS is the problem: real duty is generated by a
      closed-loop controller, so 83 days contain far fewer independent duty
      patterns than 3772 windows suggests, and there is nothing to generalise
      from.

This settles it. A known ODE (alice at the SHIPPED parameters) generates the
target, so the right answer exists exactly and is reachable by construction.
Then frank is fitted to it under two excitation regimes:

  --duty real     the recorded controller duty. Narrow excitation.
  --duty random   piecewise-constant random duty. Rich excitation.

Read the 2x2:
  frank fails BOTH        -> (a). frank is broken; void every frank number.
  frank fails real, wins
    random                -> (b). Excitation-limited. frank's 0.441 says
                             nothing about an information ceiling, and the fix
                             is real PRBS duty on fc1, not more parameters.
  frank wins BOTH         -> neither. frank can generalise on this corpus, so
                             its real-data loss IS a real result.

alice is fitted alongside as the pipeline control: it is the teacher's own
structure, so it MUST recover to ~0. If alice does not, the harness is broken
and nothing else on the page means anything.

NOT the same thing as training frank on synthetic data. This never touches the
bake-off corpus -- the teacher's output is the target here, so anything learned
is learned about the TEACHER. Using this to augment the real corpus would
distil the physics into frank and guarantee the answer the bake-off is asking.

    .venv/bin/python scripts/bakeoff/recover.py --candidates frank --duty random
"""
import argparse, json
import numpy as np
import torch

from run import (CHANNELS, EWMAS, HORIZONS, Alice, ah_sat, ewma, fit,
                 horizon_mse, load, rollout, windows)

TEACHER_TAU_S = 600.0        # the teacher's own mixing lag, not fitted here


def random_duty(duty, dt_s, seed):
    """Piecewise-constant random duty: a uniform level held for 30 s to 10 min.
    Matches the recorded duty's range and mean rate of change is far higher --
    that is the whole point, it is the excitation the controller never gives."""
    rs = np.random.RandomState(seed)
    B, T = duty.shape
    out = np.zeros((B, T))
    for i in range(B):
        t = 0
        while t < T:
            n = int(rs.randint(int(30 / dt_s), int(600 / dt_s)))
            out[i, t:t + n] = rs.rand()
            t += n
    return torch.tensor(out)


def teach(b, dt_s, mode, seed, dates):
    """Replace the recorded RH with what the teacher ODE says it should be.

    The exogenous channels must stay CONSISTENT with the duty they describe:
    u_ew5/30/60 are EWMAs of duty, so randomising duty without recomputing
    them hands frank stale history that contradicts its own input. That is a
    corrupted experiment, not a harder one."""
    b = dict(b)
    if mode == 'random':
        b['duty'] = random_duty(b['duty'].numpy(), dt_s, seed)
        for k, (src, tau) in EWMAS.items():
            if src == 'duty':
                b[k] = torch.tensor(ewma(b['duty'].numpy(), tau, dt_s, dates))
    with torch.no_grad():
        rh = rollout(Alice(), torch.tensor(TEACHER_TAU_S), b, dt_s)
    b['rh'] = rh
    b['ah0'] = rh[:, 0] / 100.0 * ah_sat(b['temp'][:, 0])
    return b


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--candidates', default='alice,frank')
    ap.add_argument('--duty', default='real', choices=['real', 'random'])
    ap.add_argument('--split', default='inter')
    ap.add_argument('--steps', type=int, default=1500)
    ap.add_argument('--lr', type=float, default=0.05)
    ap.add_argument('--seed', type=int, default=0)
    ap.add_argument('--out', default='')
    a = ap.parse_args()

    tr_d, te_d, dt_s = load(a.split)
    tr_d = teach(tr_d, dt_s, a.duty, a.seed, tr_d['dates'])
    te_d = teach(te_d, dt_s, a.duty, a.seed + 500, te_d['dates'])

    # same day-wise fit/validation split as run.main -- splitting by window
    # index leaks half a window into validation.
    allw = windows(tr_d, dt_s, max(HORIZONS))
    n = len(allw['ah'])
    days = np.unique(allw['day'].numpy())
    rs = np.random.RandomState(1000 + a.seed)
    vdays = set(rs.choice(days, max(1, len(days) // 5), replace=False).tolist())
    vm = np.array([d in vdays for d in allw['day'].numpy()])
    cut = lambda m: {k: (v[m] if hasattr(v, '__len__') and len(v) == n else v)
                     for k, v in allw.items()}
    tr, va = cut(~vm), cut(vm)
    te = windows(te_d, dt_s, max(HORIZONS))
    ks = [int(h * 60 / dt_s) for h in HORIZONS]
    base = [float(x) ** .5 for x in horizon_mse(
        te['ah0'][:, None].expand_as(te['ah']), te, ks)]
    print(f'teacher=alice(shipped)  duty={a.duty}  split={a.split}  seed={a.seed}\n'
          f'  fit {len(tr["ah"])} windows / validate {len(va["ah"])} / test {len(te["ah"])}\n'
          f'  persistence on the SYNTHETIC target: '
          f'{"  ".join(f"{b:.4f}" for b in base)} g/m3', flush=True)

    rows = []
    for name in a.candidates.split(','):
        print(f'  fitting {name}...', flush=True)
        ckpt = f'{a.out}.{name}.ckpt' if a.out else ''
        model, tau_s, e_tr, e_te, dead_s = fit(name, tr, te, dt_s, a.steps,
                                               a.lr, a.seed, ckpt, va=va)
        skill = [t / b for t, b in zip(e_te, base)]
        rows.append(dict(candidate=name, duty=a.duty, split=a.split, seed=a.seed,
                         teacher='alice_shipped', tau_s=tau_s, dead_time_s=dead_s,
                         horizons_min=list(HORIZONS), train_err=e_tr,
                         test_err=e_te, skill=skill, skill_worst=max(skill),
                         n_params=sum(p.numel() for p in model.parameters()) + 1))
        print(f'    {name}: worst-horizon skill {max(skill):.4f}  '
              f'(recovered if << 1 and alice ~ 0)', flush=True)
    if a.out:
        json.dump(rows, open(a.out, 'w'), indent=1)
        print(f'wrote {a.out}')


if __name__ == '__main__':
    main()
