version: '3.8'

services:
  openmct:
    build: .
    # ports:  # Removed - using host networking in override
    #   - "8080:8080"
    environment:
      - ROS_DOMAIN_ID=69
      - ROS_LOCALHOST_ONLY=0

  life_support:
    build:
      context: ./src/chambers/fc-core
    environment:
      - ROS_DOMAIN_ID=69
      - ROS_LOCALHOST_ONLY=0
    entrypoint: ["/bin/bash"] 