// Phase 28 D-17 Layer 2: persistence (explicit Save-to-repo per D-19).
//
// Layer 2 transport is locked by 28-01-SPIKE.md §C / D-B1: fc_buffer HTTP relay.
// The bridge container has no `ssh` binary (probe in §B); fc_buffer.py already
// runs on fc1 as `ubuntu` and binds 172.16.10.5:8765 (D-B5). We add one more
// route there (POST /control/persist) and forward to it from this module.
//
// Same allowlist as control_param.js — Layer 1 and Layer 2 share validation
// rules; the writer side (fc_buffer) ALSO enforces a path allowlist (T-28-20
// defense in depth).

'use strict';

const yaml = require('js-yaml');
const cp = require('./control_param');

const OVERLAY_PATH = process.env.FC_RUNTIME_OVERLAY || '/var/lib/fc-core/runtime_overrides.yaml';
const FC_BUFFER_HOST = process.env.FC_BUFFER_HOST || '172.16.10.5';
const FC_BUFFER_PORT = Number(process.env.FC_BUFFER_PORT || 8765);

const ALLOWED_NODES = new Set(['fc_controller']);
const MAX_PARAMS = 20;

// mergeOverlay: existing parsed yaml object (may be {} or null) + array of
// {param, value} entries. Returns new yaml object with fc_controller.ros__parameters
// populated as flat dotted-key entries (D-03 — keys are NOT nested under modes/fruiting).
function mergeOverlay(existing, entries) {
    const out = (existing && typeof existing === 'object') ? structuredClone(existing) : {};
    out.fc_controller = out.fc_controller || {};
    out.fc_controller.ros__parameters = out.fc_controller.ros__parameters || {};
    const params = out.fc_controller.ros__parameters;
    for (const { param, value } of entries) {
        params[param] = value;
    }
    return out;
}

// renderOverlay: yaml string with header. js-yaml dumps NaN → `.nan` natively
// (verified: node -e "yaml.dump({a:NaN})" → "a: .nan"). Defensive normalization
// kept for safety in case js-yaml options change.
function renderOverlay(obj, opts = {}) {
    const ts = opts.timestamp || new Date().toISOString();
    const header =
        '# AUTO-GENERATED by bridge POST /control/persist — do not hand-edit.\n' +
        `# Last write: ${ts}\n`;
    let body = yaml.dump(obj, { lineWidth: 200, sortKeys: true });
    body = body.replace(/: NaN$/gm, ': .nan').replace(/: nan$/gm, ': .nan');
    return header + body;
}

// Strip the timestamp comment for byte-equality idempotency comparisons.
function stripHeader(s) {
    return s.replace(/^# .*\n/gm, '');
}

function makeHandler(transport, opts = {}) {
    const overlayPath = opts.overlayPath || OVERLAY_PATH;
    return async function handle(req, res) {
        const body = req.body || {};
        if (!ALLOWED_NODES.has(body.node)) {
            return res.status(400).json({ error: `node ${JSON.stringify(body.node)} not allowlisted` });
        }
        let entries;
        if (Array.isArray(body.params)) entries = body.params;
        else if (body.param != null) entries = [{ param: body.param, value: body.value }];
        else return res.status(400).json({ error: 'body must include `param`+`value` or `params: []`' });

        if (entries.length === 0) return res.status(400).json({ error: 'params array is empty' });
        if (entries.length > MAX_PARAMS) return res.status(400).json({ error: `too many params (max ${MAX_PARAMS})` });

        for (const { param, value } of entries) {
            const v = cp.validate(param, value);
            if (!v.ok) return res.status(400).json({ error: v.reason, rejected_param: param });
        }

        try {
            const existing = await transport.read(overlayPath).catch(() => null);
            const parsed = existing ? (yaml.load(existing) || {}) : {};
            const merged = mergeOverlay(parsed, entries);
            const rendered = renderOverlay(merged);
            await transport.atomicWrite(overlayPath, rendered);
            return res.json({
                ok: true,
                persisted: entries.map(({ param, value }) => ({ param, value })),
                path: overlayPath,
            });
        } catch (e) {
            return res.status(500).json({ error: `persist failed: ${e.message}` });
        }
    };
}

// Branch B (locked per D-B1): fc_buffer HTTP relay transport. The bridge POSTs
// the rendered overlay yaml to fc_buffer.py's POST /control/persist route.
function makeHttpTransport(opts = {}) {
    const host = opts.host || FC_BUFFER_HOST;
    const port = opts.port || FC_BUFFER_PORT;
    const fetchFn = opts.fetch || global.fetch;
    if (typeof fetchFn !== 'function') {
        throw new Error('global fetch unavailable; bridge requires Node >= 18');
    }
    return {
        async read(p) {
            const url = `http://${host}:${port}/control/overlay?path=${encodeURIComponent(p)}`;
            const r = await fetchFn(url);
            if (r.status === 404) return null;
            if (!r.ok) throw new Error(`overlay read ${r.status}`);
            return await r.text();
        },
        async atomicWrite(p, content) {
            const url = `http://${host}:${port}/control/persist`;
            const r = await fetchFn(url, {
                method: 'POST',
                headers: { 'content-type': 'application/json' },
                body: JSON.stringify({ path: p, content }),
            });
            if (!r.ok) {
                const txt = await r.text().catch(() => '');
                throw new Error(`persist write ${r.status}: ${txt}`);
            }
        },
    };
}

module.exports = {
    OVERLAY_PATH,
    MAX_PARAMS,
    mergeOverlay,
    renderOverlay,
    stripHeader,
    makeHandler,
    makeHttpTransport,
};
