"""fit_q_c recovers Q and C from samples generated by the model it fits.

Run: ./.venv/bin/python -m pytest scripts/test_fit_chamber_model.py
"""
import importlib.util
import random
from pathlib import Path

import pytest

_spec = importlib.util.spec_from_file_location(
    'fit_chamber_model', Path(__file__).with_name('fit-chamber-model.py'))
fcm = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(fcm)
V = fcm.CHAMBER_VOLUME_M3


def _samples(q, c, n=4000, seed=0):
    rng = random.Random(seed)
    out = []
    for _ in range(n):
        grad = rng.uniform(0.2, 3.0)
        dtemp = rng.uniform(-1.5, 1.5)
        dah_dt = (-q * grad + c * dtemp) / V + rng.gauss(0, 0.02)
        out.append({'ah_in': 8.0 + grad, 'ah_out': 8.0, 'dtemp_dt': dtemp,
                    'dah_dt': dah_dt, 'duty': 0.0, 'duty_app': 0.0})
    return out


def test_fit_q_c_recovers_both_coefficients():
    (q, c), n = fcm.fit_q_c(_samples(q=0.35, c=2.8))
    assert n == 4000
    assert q == pytest.approx(0.35, abs=0.03)
    assert c == pytest.approx(2.8, abs=0.1)


def test_fit_q_c_with_no_temperature_change_matches_fit_q():
    s = [dict(x, dtemp_dt=0.0) for x in _samples(q=0.9, c=0.0)]
    (q, _c), _ = fcm.fit_q_c(s)
    q1, _ = fcm.fit_q(s)
    assert q == pytest.approx(q1, rel=1e-6)


def test_fit_f_regression_removes_the_surface_term():
    """Active samples: V*dAH/dt = F*u - Q*grad + C*dT/dt. With C passed in,
    the regression must recover F; without it F absorbs the temperature term."""
    rng = random.Random(1)
    q, c, f = 0.9, 2.8, 6.8
    s = []
    for _ in range(4000):
        grad, dtemp, u = rng.uniform(0.2, 3.0), rng.uniform(0.5, 1.5), rng.uniform(0.05, 0.6)
        s.append({'ah_in': 8.0 + grad, 'ah_out': 8.0, 'dtemp_dt': dtemp, 'duty': u,
                  'duty_app': u, 'dah_dt': (f * u - q * grad + c * dtemp) / V})
    f_fit, _ = fcm.fit_f_regression(s, q, c)
    assert f_fit == pytest.approx(f, rel=1e-6)
    f_wrong, _ = fcm.fit_f_regression(s, q)
    assert f_wrong > f * 1.2
